### ISSUE TITLE
Improvement on mod operation

### ISSUE THREAD

**Issue by NickJian** [SodaLabs/android-looping-pager-layoutmanager#8]
https://github.com/SodaLabs/android-looping-pager-layoutmanager/blob/ca83ba6f658bc958f750cb1d20d452f755fe86cb/pager/src/main/java/co/sodalabs/pager/LayoutExtensions.kt#L46

This can be done without while loop like: 
int i = -1 % 2;
if (i<0) i += 2;

**Comment by tcw165** [comment]
Thanks! It's a good suggestion and really help with the performance. I'll patch this soon.

**Comment by tcw165** [comment]
@NickJian Here is the PR, https://github.com/SodaLabs/android-looping-pager-layoutmanager/pull/9

**Comment by tcw165** [comment]
We'll probably cut another release as we accumulate three fixes.

**Comment by tcw165** [comment]
The PR is merged so I'm gonna close this issue. Thanks again @NickJian
